In [1]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains as AC
import time

In [2]:
driver=webdriver.Edge()
driver.get("https://www.imdb.com/search/title/?title_type=feature&genres=sci-fi&release_date=2024-01-01,2024-12-31")
time.sleep(5)
movie_name=driver.find_elements(By.XPATH, '//*[@id="__next"]/main/div[2]/div[3]/section/section/div/section/section/div[2]/div/section/div[2]/div[2]/ul/li')

def more_list():
    try:
        more_button=driver.find_element(By.XPATH,'//*[@id="__next"]/main/div[2]/div[3]/section/section/div/section/section/div[2]/div/section/div[2]/div[2]/div[2]/div/span/button/span/span')
        AC(driver).move_to_element(more_button).perform()
        more_button.click()
        time.sleep(5)
        return True
    except:
        return False

while more_list():
    print("Click for more")

print("NO more")

Click for more
Click for more
Click for more
Click for more
Click for more
Click for more
Click for more
Click for more
Click for more
Click for more
Click for more
NO more

In [3]:
movie_name=driver.find_elements(By.XPATH, '//*[@id="__next"]/main/div[2]/div[3]/section/section/div/section/section/div[2]/div/section/div[2]/div[2]/ul/li')

In [4]:
len(movie_name)

590

In [5]:
time.sleep(3)
titles=[]
ratings=[]
votings=[]
durations=[]
movie_name=driver.find_elements(By.XPATH, '//*[@id="__next"]/main/div[2]/div[3]/section/section/div/section/section/div[2]/div/section/div[2]/div[2]/ul/li')
for movies in movie_name: 
    try:  
        title=movies.find_element(By.XPATH,'./div/div/div/div[1]/div[2]/div[1]/a/h3').text
        rating=movies.find_element(By.XPATH,'./div/div/div/div[1]/div[2]/span/div/span/span[1]').text
        voting=movies.find_element(By.XPATH,'./div/div/div/div[1]/div[2]/span/div/span/span[2]').text
        duration=movies.find_element(By.XPATH,'./div/div/div/div[1]/div[2]/div[2]/span[2]').text
        titles.append(title)
        ratings.append(rating)
        votings.append(voting)
        durations.append(duration)
    except:
        print("Error")
        continue

Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error

In [6]:
SCIFI_Movies=pd.DataFrame({
    "Title":titles,
    "Rating":ratings,
    "Voting":votings,
    "Duration":durations
})

SCIFI_Movies

                                Title Rating   Voting Duration
0                    1. The Substance    7.3   (244K)   2h 21m
1             2. Sonic the Hedgehog 3    7.0    (43K)   1h 50m
2                   3. The Wild Robot    8.2   (134K)   1h 42m
3          4. Furiosa: A Mad Max Saga    7.5   (269K)   2h 28m
4                   5. Alien: Romulus    7.1   (226K)   1h 59m
..                                ...    ...      ...      ...
321  491. Kyle and the Last Emerald 2    8.4      (6)      15m
322               502. Captain Corpse    7.6      (9)   1h 45m
323    517. PW V: Tears of the Fallen    8.2     (11)       1h
324                       557. Morana    6.2     (26)   1h 59m
325                571. The Blinkless    7.8     (12)      59m

[326 rows x 4 columns]

In [7]:
SCIFI_Movies["Genre"]="SCI-FI"
SCIFI_Movies

                                Title Rating   Voting Duration   Genre
0                    1. The Substance    7.3   (244K)   2h 21m  SCI-FI
1             2. Sonic the Hedgehog 3    7.0    (43K)   1h 50m  SCI-FI
2                   3. The Wild Robot    8.2   (134K)   1h 42m  SCI-FI
3          4. Furiosa: A Mad Max Saga    7.5   (269K)   2h 28m  SCI-FI
4                   5. Alien: Romulus    7.1   (226K)   1h 59m  SCI-FI
..                                ...    ...      ...      ...     ...
321  491. Kyle and the Last Emerald 2    8.4      (6)      15m  SCI-FI
322               502. Captain Corpse    7.6      (9)   1h 45m  SCI-FI
323    517. PW V: Tears of the Fallen    8.2     (11)       1h  SCI-FI
324                       557. Morana    6.2     (26)   1h 59m  SCI-FI
325                571. The Blinkless    7.8     (12)      59m  SCI-FI

[326 rows x 5 columns]

In [8]:
#Converting Voting into int
def convert_voting(value):
    value = value.strip().replace('(', '').replace(')', '')  # Remove spaces and parentheses
    if 'K' in value:
        return int(float(value.replace('K', '')) * 1000)  # Convert 'K' to a number
    elif value.isdigit():  # Check if it's a pure number
        return int(value)
    else:
        return None

SCIFI_Movies["Voting"]=SCIFI_Movies["Voting"].apply(convert_voting)

In [9]:
#Converting Duration into time
def convert_to_sql_time(value):
    value = value.lower().strip()  
    if 'h' in value or 'm' in value:
        value = value.replace('h', '').replace('m', '')  
        parts = value.split() 
        hours = int(parts[0]) if len(parts) > 0 and parts[0].isdigit() else 0
        minutes = int(parts[1]) if len(parts) > 1 and parts[1].isdigit() else 0
        return f"{hours:02d}:{minutes:02d}:00"  
    return None

SCIFI_Movies["Duration"]= SCIFI_Movies["Duration"].apply(convert_to_sql_time)

In [10]:
SCIFI_Movies.to_csv("project_scifi.csv",index=False)