In [1]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains as AC
import time

In [2]:
driver=webdriver.Edge()
driver.get("https://www.imdb.com/search/title/?title_type=feature&genres=musical&release_date=2024-01-01,2024-12-31")
time.sleep(5)
movie_name=driver.find_elements(By.XPATH, '//*[@id="__next"]/main/div[2]/div[3]/section/section/div/section/section/div[2]/div/section/div[2]/div[2]/ul/li')

def more_list():
    try:
        more_button=driver.find_element(By.XPATH,'//*[@id="__next"]/main/div[2]/div[3]/section/section/div/section/section/div[2]/div/section/div[2]/div[2]/div[2]/div/span/button/span/span')
        AC(driver).move_to_element(more_button).perform()
        more_button.click()
        time.sleep(5)
        return True
    except:
        return False

while more_list():
    print("Click for more")

print("NO more")

Click for more
Click for more
Click for more
NO more

In [3]:
movie_name=driver.find_elements(By.XPATH, '//*[@id="__next"]/main/div[2]/div[3]/section/section/div/section/section/div[2]/div/section/div[2]/div[2]/ul/li')

In [4]:
len(movie_name)

167

In [5]:
time.sleep(3)
titles=[]
ratings=[]
votings=[]
durations=[]
movie_name=driver.find_elements(By.XPATH, '//*[@id="__next"]/main/div[2]/div[3]/section/section/div/section/section/div[2]/div/section/div[2]/div[2]/ul/li')
for movies in movie_name: 
    try:  
        title=movies.find_element(By.XPATH,'./div/div/div/div[1]/div[2]/div[1]/a/h3').text
        rating=movies.find_element(By.XPATH,'./div/div/div/div[1]/div[2]/span/div/span/span[1]').text
        voting=movies.find_element(By.XPATH,'./div/div/div/div[1]/div[2]/span/div/span/span[2]').text
        duration=movies.find_element(By.XPATH,'./div/div/div/div[1]/div[2]/div[2]/span[2]').text
        titles.append(title)
        ratings.append(rating)
        votings.append(voting)
        durations.append(duration)
    except:
        print("Error")
        continue

Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error

In [6]:
MUSIC_Movies=pd.DataFrame({
    "Title":titles,
    "Rating":ratings,
    "Voting":votings,
    "Duration":durations
})

MUSIC_Movies

                                                Title Rating   Voting Duration
0                                     1. Emilia Pérez    5.5    (68K)   2h 12m
1                                           2. Wicked    7.6   (125K)   2h 40m
2                                          3. Moana 2    6.8    (76K)   1h 40m
3                            4. Mufasa: The Lion King    6.7    (38K)   1h 58m
4                                       5. Better Man    7.6    (14K)   2h 15m
..                                                ...    ...      ...      ...
57                                  93. Call Me Agnes    7.1     (10)   1h 34m
58                                    94. Iyus Jenius    8.8      (6)   1h 22m
59  96. The Clashing Elements: Saviors of the Mult...    5.6      (5)   1h 31m
60  112. El musical de los 80s y los 90s. La película    5.4      (6)   1h 20m
61                      120. Bryson, the Demon Slayer    4.4     (11)      59m

[62 rows x 4 columns]

In [7]:
MUSIC_Movies["Genre"]="Music"
MUSIC_Movies

,Title,Rating,Voting,Duration,Genre
0,1. Emilia Pérez,5.5,(68K),2h 12m,Music
1,2. Wicked,7.6,(125K),2h 40m,Music
2,3. Moana 2,6.8,(76K),1h 40m,Music
3,4. Mufasa: The Lion King,6.7,(38K),1h 58m,Music
4,5. Better Man,7.6,(14K),2h 15m,Music
...,...,...,...,...,...
57,93. Call Me Agnes,7.1,(10),1h 34m,Music
58,94. Iyus Jenius,8.8,(6),1h 22m,Music
59,96. The Clashing Elements: Saviors of the Mult...,5.6,(5),1h 31m,Music
60,112. El musical de los 80s y los 90s. La película,5.4,(6),1h 20m,Music
61,"120. Bryson, the Demon Slayer",4.4,(11),59m,Music

In [8]:
#Converting Voting into int
def convert_voting(value):
    value = value.strip().replace('(', '').replace(')', '')  # Remove spaces and parentheses
    if 'K' in value:
        return int(float(value.replace('K', '')) * 1000)  # Convert 'K' to a number
    elif value.isdigit():  # Check if it's a pure number
        return int(value)
    else:
        return None

MUSIC_Movies["Voting"]=MUSIC_Movies["Voting"].apply(convert_voting)

In [9]:
#Converting Duration into time
def convert_to_sql_time(value):
    value = value.lower().strip()  
    if 'h' in value or 'm' in value:
        value = value.replace('h', '').replace('m', '')  
        parts = value.split() 
        hours = int(parts[0]) if len(parts) > 0 and parts[0].isdigit() else 0
        minutes = int(parts[1]) if len(parts) > 1 and parts[1].isdigit() else 0
        return f"{hours:02d}:{minutes:02d}:00"  
    return None
MUSIC_Movies["Duration"]= MUSIC_Movies["Duration"].apply(convert_to_sql_time)

In [10]:
MUSIC_Movies.to_csv("project_music.csv",index=False)